
Given a string s consisting of words and spaces, return the length of the last word in the string.
//https://leetcode.com/problems/length-of-last-word/description/
CLASS ZCL_LENGTH_LAST_WORD DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES IF_OO_ADT_CLASSRUN.
    METHODS: LASTWORDLENGTH IMPORTING INPUT_STRING          TYPE STRING
                             RETURNING VALUE(RESULT_LENGTH) TYPE I.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS ZCL_LENGTH_LAST_WORD IMPLEMENTATION.
  METHOD IF_OO_ADT_CLASSRUN~MAIN.
    OUT->WRITE( LASTWORDLENGTH( 'ABAP Cloud Class' ) ).
  ENDMETHOD.

  METHOD LASTWORDLENGTH.
    SPLIT INPUT_STRING AT SPACE INTO TABLE DATA(WORDS).
    DATA(COUNTS) = LINES( WORDS ).
    RESULT_LENGTH = STRLEN( WORDS[ COUNTS ] ).
  ENDMETHOD.
ENDCLASS.
